spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/Zaineb_Majdi
#          on peut le recuperer depuis ce lien
#  http://localhost:9000/realms/Zaineb_Majdi/.well-known/openid-configuration
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: zaineb-rest-api
      principle-attribute: preferred_username
